// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH1Iv9oyw0uA_ONK6t9j0zK8ng3KHxPEM',
    appId: '1:567249470284:web:a50874098123a1039645e9',
    messagingSenderId: '567249470284',
    projectId: 'naka-memories',
    authDomain: 'naka-memories.firebaseapp.com',
    storageBucket: 'naka-memories.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs282VXbispjLiC9_ooqQ7g8hJ6dR0qk4',
    appId: '1:567249470284:android:85235c885fade8859645e9',
    messagingSenderId: '567249470284',
    projectId: 'naka-memories',
    storageBucket: 'naka-memories.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJLZ1uCSVwUbaK1Dfz3TyKxn_6ZzCbrc',
    appId: '1:567249470284:ios:96e43ba688d743e69645e9',
    messagingSenderId: '567249470284',
    projectId: 'naka-memories',
    storageBucket: 'naka-memories.firebasestorage.app',
    iosBundleId: 'com.example.nakaMemories',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIJLZ1uCSVwUbaK1Dfz3TyKxn_6ZzCbrc',
    appId: '1:567249470284:ios:96e43ba688d743e69645e9',
    messagingSenderId: '567249470284',
    projectId: 'naka-memories',
    storageBucket: 'naka-memories.firebasestorage.app',
    iosBundleId: 'com.example.nakaMemories',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAH1Iv9oyw0uA_ONK6t9j0zK8ng3KHxPEM',
    appId: '1:567249470284:web:5cef69f99d163b3e9645e9',
    messagingSenderId: '567249470284',
    projectId: 'naka-memories',
    authDomain: 'naka-memories.firebaseapp.com',
    storageBucket: 'naka-memories.firebasestorage.app',
  );
}
